// Catalog of every AstroSeer-API-backed feature we surface to the
// customer on /discover. Each entry drives:
//   - the dashboard card (label + group + one-glyph monochrome icon)
//   - the detail page (description + bullet list of sections)
//   - the price (override key on settings/config.<priceKey>)
//   - the relay action that produces the deliverable
//
// Icons are intentionally simple line emoji so the cards render
// single-colour on every device — no colourful PNG zoo. The
// dashboard CSS forces a monochrome shadow + tint anyway.
export const FEATURE_GROUPS = [
  ['core',      'Core Vedic'],
  ['vargas',    'Divisional charts'],
  ['systems',   'Vedic systems'],
  ['extra',     'Extra systems'],
  ['life',      'Life & guidance'],
  ['remedies',  'Remedies & rituals'],
  ['reports',   'Bundled reports'],
];

export const FEATURES = [
  // --- Core Vedic ---
  { id: 'kundli_basic', group: 'core', icon: 'om',
    title: 'Vedic Kundli (Janma)',
    blurb: 'Birth chart with Lagna, planets, nakshatras, panchang.',
    priceKey: 'kundli_free_price', defaultPrice: 0,
    sections: ['Basic + Avakhada + Panchang', 'Lagna chart D1',
      'Planets sign + nakshatra', 'Yogas + doshas overview'] },
  { id: 'kundli_lagna', group: 'core', icon: 'star',
    title: 'Lagna / Ascendant Report',
    blurb: 'Detailed ascendant personality, body, mind.',
    priceKey: 'kundli_lagna_price', defaultPrice: 0,
    sections: ['Lagna sign and lord', 'Body, mind, temperament',
      'Career indications by ascendant'] },
  { id: 'moon_nakshatra', group: 'core', icon: 'moon',
    title: 'Moon Nakshatra Deep-Dive',
    blurb: 'Detailed treatment of the native&apos;s Moon nakshatra.',
    priceKey: 'moon_nakshatra_price', defaultPrice: 49,
    sections: ['Nakshatra lord and deity', 'Pada-level traits',
      'Compatible nakshatras', 'Career and money signals'] },
  { id: 'dasha_drilldown', group: 'core', icon: 'clock',
    title: '4-Level Vimshottari Dasha',
    blurb: 'Maha to Sookshma drilldown with dates and predictions.',
    priceKey: 'dasha_drilldown_price', defaultPrice: 0,
    sections: ['All 9 mahas', 'Antar, pratyantar, sookshma tree',
      'Current period analysis'] },

  // --- Divisional charts ---
  { id: 'd9_navamsa', group: 'vargas', icon: 'rings',
    title: 'D9 Navamsa — Marriage',
    blurb: 'Marriage and dharma chart with detailed reading.',
    priceKey: 'd9_navamsa_price', defaultPrice: 49,
    sections: ['Navamsa chart', '7th house deep analysis',
      'Spouse character indications'] },
  { id: 'd10_dasamsa', group: 'vargas', icon: 'briefcase',
    title: 'D10 Dasamsa — Career',
    blurb: 'Career and profession chart with timing windows.',
    priceKey: 'd10_dasamsa_price', defaultPrice: 49,
    sections: ['Dasamsa chart', '10th house deep analysis',
      'Industry and job role pointers'] },
  { id: 'divisional_all', group: 'vargas', icon: 'grid',
    title: 'All 16 Divisional Charts',
    blurb: 'D1 to D60 charts in a single bundled report.',
    priceKey: 'divisional_all_price', defaultPrice: 99,
    sections: ['Hora, Drekkana, Chaturthamsa', 'Saptamsa, Navamsa, Dasamsa',
      'Dvadasamsa, Shodasamsa, Vimsamsa', 'Plus 7 more divisional charts'] },

  // --- Vedic systems ---
  { id: 'kp_system', group: 'systems', icon: 'compass',
    title: 'KP (Krishnamurti Paddhati)',
    blurb: 'Bhav Chalit chart, ruling planets and cusps detail.',
    priceKey: 'kp_system_price', defaultPrice: 49,
    sections: ['Bhav Chalit chart', 'Ruling planets', 'Cusps table',
      'Sub-lord analysis'] },
  { id: 'ashtakvarga', group: 'systems', icon: 'grid',
    title: 'Ashtakvarga (BAV + SAV)',
    blurb: 'Bindu strength analysis per house from every BAV.',
    priceKey: 'ashtakvarga_price', defaultPrice: 49,
    sections: ['Sarvashtakvarga grid', '8 BAV mini-charts',
      'Strong and weak houses', 'Transit overlay'] },
  { id: 'yogas_doshas', group: 'systems', icon: 'thunder',
    title: 'Yogas + Doshas Audit',
    blurb: 'Every classical yoga and dosha present in the chart.',
    priceKey: 'yogas_doshas_price', defaultPrice: 49,
    sections: ['Mahapurusha + Raj yogas', 'Mangal, Kalsarp, Sade Sati',
      'Remedies per dosha'] },
  { id: 'panchang_birth', group: 'systems', icon: 'calendar',
    title: 'Panchang at Birth',
    blurb: 'Tithi, Karan, Yoga, Nakshatra, Rahu / Gulika / Yamaganda.',
    priceKey: 'panchang_birth_price', defaultPrice: 0,
    sections: ['Tithi + Paksha', 'Karan + Yoga', 'Nakshatra + pada',
      'Sunrise, sunset, moonrise, moonset', 'Rahu kaalam window'] },

  // --- Extra systems ---
  { id: 'chinese_zodiac', group: 'extra', icon: 'dragon',
    title: 'Chinese Zodiac Reading',
    blurb: 'Animal, element and Yin/Yang polarity from the birth year.',
    priceKey: 'chinese_zodiac_price', defaultPrice: 29,
    sections: ['Animal totem + element', 'Yin / Yang polarity',
      'Compatible signs', 'Year-by-year prospects'] },
  { id: 'western_astro', group: 'extra', icon: 'sun',
    title: 'Western Astrology Snapshot',
    blurb: 'Tropical Sun, Moon and Rising sign with Western interpretation.',
    priceKey: 'western_astro_price', defaultPrice: 29,
    sections: ['Tropical Sun, Moon, Rising', 'Element + modality',
      'Big Three personality reading'] },
  { id: 'face_reading', group: 'extra', icon: 'face',
    title: 'Face Reading (Mukha Samudrika)',
    blurb: 'Self-guide for face reading across 9 facial zones.',
    priceKey: 'face_reading_price', defaultPrice: 49,
    sections: ['9-zone face map', 'What each feature reveals',
      'How to self-assess'] },
  { id: 'palm_reading', group: 'extra', icon: 'hand',
    title: 'Palm Reading (Hastha Samudrika)',
    blurb: 'Self-guide for palmistry: 7 major lines, 7 mounts, fingers.',
    priceKey: 'palm_reading_price', defaultPrice: 49,
    sections: ['7 major lines', '7 mounts of the palm', 'Finger shapes',
      'Hand reading method'] },
  { id: 'colour_crystal', group: 'extra', icon: 'gem',
    title: 'Colour and Crystal Therapy',
    blurb: 'Seven-chakra colour and crystal reference for self-balancing.',
    priceKey: 'colour_crystal_price', defaultPrice: 29,
    sections: ['Chakra colours', 'Crystal per chakra', 'How to use them'] },
  { id: 'tarot_lifecard', group: 'extra', icon: 'card',
    title: 'Tarot Life-Path Card',
    blurb: 'Major Arcana card derived from your life-path number.',
    priceKey: 'tarot_lifecard_price', defaultPrice: 29,
    sections: ['Your life-path card', 'Theme + guidance',
      'Year card overlay'] },

  // --- Life & guidance ---
  { id: 'vastu', group: 'life', icon: 'compass',
    title: 'Vastu Directional Guidance',
    blurb: 'Eight-direction Vastu reference plus personal sleep direction.',
    priceKey: 'vastu_price', defaultPrice: 49,
    sections: ['8-direction Vastu map', 'Personal sleep + work direction',
      'Quick room layout fixes'] },
  { id: 'numerology', group: 'life', icon: 'numerology',
    title: 'Numerology Deep Profile',
    blurb: 'Driver, conductor, life-path, soul, destiny — full numerology.',
    priceKey: 'numerology_price', defaultPrice: 49,
    sections: ['Driver number', 'Conductor number', 'Life-path number',
      'Soul + destiny + personality numbers',
      'Lucky colour + day + gemstone'] },
  { id: 'lucky_mobile', group: 'life', icon: 'phone',
    title: 'Lucky Mobile Number',
    blurb: 'Personalised mobile-number compatibility + lucky suggestions.',
    priceKey: 'lucky_mobile_price', defaultPrice: 49,
    sections: ['Compatibility check for your current number',
      '5 personalised lucky number patterns',
      'When to change your number'] },
  { id: 'name_correction', group: 'life', icon: 'letter',
    title: 'Name Correction',
    blurb: 'Optimal name spelling based on date of birth and chart.',
    priceKey: 'name_correction_price', defaultPrice: 99,
    sections: ['Current name analysis',
      '3 corrected name suggestions',
      'How to phase the change in'] },
  { id: 'baby_name', group: 'life', icon: 'baby',
    title: 'Baby Name Suggestions',
    blurb: 'Auspicious baby names based on nakshatra + numerology.',
    priceKey: 'baby_name_price', defaultPrice: 99,
    sections: ['Nakshatra-based syllables',
      '20 name suggestions with meanings',
      'Numerology-checked'] },
  { id: 'career_finance', group: 'life', icon: 'briefcase',
    title: 'Career and Finance Deep Dive',
    blurb: '10th, 2nd, 11th, 6th house + dasha career timing.',
    priceKey: 'kundli_careerFinance_price', defaultPrice: 99,
    sections: ['10th house karma analysis',
      '2nd house wealth + 11th house gains',
      'Business vs job indication',
      'Finance windows for 5 years'] },
  { id: 'lifetime_report', group: 'life', icon: 'book',
    title: 'Lifetime Vedic Report',
    blurb: '300+ pages: every dasha, every life area, lifetime.',
    priceKey: 'kundli_lifetime_price', defaultPrice: 299,
    sections: ['All 9 mahas with antardashas',
      'Decade-by-decade outlook',
      'Marriage, child, career, finance, health',
      'Sade Sati windows lifetime'] },

  // --- Remedies & rituals ---
  { id: 'gemstone', group: 'remedies', icon: 'gem',
    title: 'Gemstone Consultation',
    blurb: 'Birthstone + remedial stones based on planetary strength.',
    priceKey: 'gemstone_price', defaultPrice: 49,
    sections: ['Birthstone by Lagna',
      'Remedial stones for weak planets',
      'How to wear them'] },
  { id: 'mantra', group: 'remedies', icon: 'mantra',
    title: 'Personal Mantras',
    blurb: 'Beej and stotra mantras keyed to your weak planets.',
    priceKey: 'mantra_price', defaultPrice: 49,
    sections: ['Beej mantra per planet',
      'When and how to chant',
      'Stotra suggestions'] },
  { id: 'lal_kitab', group: 'remedies', icon: 'book',
    title: 'Lal Kitab Remedies',
    blurb: 'Practical daily Lal Kitab remedies matched to your chart.',
    priceKey: 'lal_kitab_price', defaultPrice: 99,
    sections: ['Planet-by-planet remedies',
      'Household-item totkas',
      'When to start, how long to continue'] },
  { id: 'rudraksha', group: 'remedies', icon: 'beads',
    title: 'Rudraksha Recommendation',
    blurb: 'Mukhi-by-mukhi rudraksha matched to your planetary needs.',
    priceKey: 'rudraksha_price', defaultPrice: 49,
    sections: ['Mukhi recommendation',
      'How to wear and energise it',
      'Combo suggestions'] },

  // --- Bundled reports ---
  { id: '12_month_forecast', group: 'reports', icon: 'calendar',
    title: '12-Month Forecast',
    blurb: 'Month-by-month predictions for the next 12 months.',
    priceKey: 'kundli_forecast12_price', defaultPrice: 50,
    sections: ['12 monthly outlooks',
      'Maha, antar, pratyantar lord per month',
      'Career, finance, love, health',
      'Important transits ahead'] },
  { id: 'compat_report', group: 'reports', icon: 'rings',
    title: 'Marriage Compatibility (Guna Milan)',
    blurb: 'Ashtakoota 36-point match across the 8 kootas.',
    priceKey: 'compat_report_price', defaultPrice: 99,
    sections: ['All 8 kootas scored', 'Total Guna out of 36',
      'Mangal-dosha cross-check', 'Suggested matching window'] },
];

// Resolve the live price for a feature by merging admin overrides
// from settings/config (same pattern shared/reportTypes.js uses).
export function featurePrice(feature, configDoc) {
  if (!feature) return 0;
  const k = feature.priceKey;
  if (configDoc && Number.isFinite(Number(configDoc[k]))) {
    return Number(configDoc[k]);
  }
  return Number(feature.defaultPrice || 0);
}

export function featureById(id) {
  return FEATURES.find((f) => f.id === id) || null;
}
