// Major Indian cities with their state, for the place-of-birth picker.
// Users can still type a city that is not listed (a state is then asked
// so it can be added for future clients).
export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
  'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
  'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
  'West Bengal', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Puducherry',
  'Chandigarh', 'Andaman and Nicobar Islands',
];

export const CITIES = [
  ['Mumbai', 'Maharashtra'], ['Pune', 'Maharashtra'],
  ['Nagpur', 'Maharashtra'], ['Nashik', 'Maharashtra'],
  ['Thane', 'Maharashtra'], ['Aurangabad', 'Maharashtra'],
  ['Solapur', 'Maharashtra'], ['Kolhapur', 'Maharashtra'],
  ['New Delhi', 'Delhi'], ['Delhi', 'Delhi'],
  ['Bengaluru', 'Karnataka'], ['Mysuru', 'Karnataka'],
  ['Mangaluru', 'Karnataka'], ['Hubli', 'Karnataka'],
  ['Belagavi', 'Karnataka'], ['Kalaburagi', 'Karnataka'],
  ['Chennai', 'Tamil Nadu'], ['Coimbatore', 'Tamil Nadu'],
  ['Madurai', 'Tamil Nadu'], ['Tiruchirappalli', 'Tamil Nadu'],
  ['Salem', 'Tamil Nadu'], ['Tirunelveli', 'Tamil Nadu'],
  ['Vellore', 'Tamil Nadu'], ['Erode', 'Tamil Nadu'],
  ['Hyderabad', 'Telangana'], ['Secunderabad', 'Telangana'],
  ['Warangal', 'Telangana'], ['Nizamabad', 'Telangana'],
  ['Karimnagar', 'Telangana'], ['Khammam', 'Telangana'],
  ['Visakhapatnam', 'Andhra Pradesh'], ['Vijayawada', 'Andhra Pradesh'],
  ['Guntur', 'Andhra Pradesh'], ['Nellore', 'Andhra Pradesh'],
  ['Tirupati', 'Andhra Pradesh'], ['Kurnool', 'Andhra Pradesh'],
  ['Rajahmundry', 'Andhra Pradesh'], ['Kakinada', 'Andhra Pradesh'],
  ['Kolkata', 'West Bengal'], ['Howrah', 'West Bengal'],
  ['Durgapur', 'West Bengal'], ['Asansol', 'West Bengal'],
  ['Siliguri', 'West Bengal'],
  ['Ahmedabad', 'Gujarat'], ['Surat', 'Gujarat'],
  ['Vadodara', 'Gujarat'], ['Rajkot', 'Gujarat'],
  ['Bhavnagar', 'Gujarat'], ['Jamnagar', 'Gujarat'], ['Gandhinagar', 'Gujarat'],
  ['Jaipur', 'Rajasthan'], ['Jodhpur', 'Rajasthan'],
  ['Udaipur', 'Rajasthan'], ['Kota', 'Rajasthan'],
  ['Ajmer', 'Rajasthan'], ['Bikaner', 'Rajasthan'],
  ['Lucknow', 'Uttar Pradesh'], ['Kanpur', 'Uttar Pradesh'],
  ['Agra', 'Uttar Pradesh'], ['Varanasi', 'Uttar Pradesh'],
  ['Prayagraj', 'Uttar Pradesh'], ['Meerut', 'Uttar Pradesh'],
  ['Ghaziabad', 'Uttar Pradesh'], ['Noida', 'Uttar Pradesh'],
  ['Bareilly', 'Uttar Pradesh'], ['Gorakhpur', 'Uttar Pradesh'],
  ['Aligarh', 'Uttar Pradesh'], ['Mathura', 'Uttar Pradesh'],
  ['Patna', 'Bihar'], ['Gaya', 'Bihar'], ['Bhagalpur', 'Bihar'],
  ['Muzaffarpur', 'Bihar'], ['Darbhanga', 'Bihar'],
  ['Bhopal', 'Madhya Pradesh'], ['Indore', 'Madhya Pradesh'],
  ['Jabalpur', 'Madhya Pradesh'], ['Gwalior', 'Madhya Pradesh'],
  ['Ujjain', 'Madhya Pradesh'], ['Sagar', 'Madhya Pradesh'],
  ['Chandigarh', 'Chandigarh'],
  ['Ludhiana', 'Punjab'], ['Amritsar', 'Punjab'],
  ['Jalandhar', 'Punjab'], ['Patiala', 'Punjab'], ['Bathinda', 'Punjab'],
  ['Gurugram', 'Haryana'], ['Faridabad', 'Haryana'],
  ['Panipat', 'Haryana'], ['Ambala', 'Haryana'], ['Hisar', 'Haryana'],
  ['Rohtak', 'Haryana'], ['Karnal', 'Haryana'],
  ['Kochi', 'Kerala'], ['Thiruvananthapuram', 'Kerala'],
  ['Kozhikode', 'Kerala'], ['Thrissur', 'Kerala'],
  ['Kollam', 'Kerala'], ['Kannur', 'Kerala'], ['Kottayam', 'Kerala'],
  ['Bhubaneswar', 'Odisha'], ['Cuttack', 'Odisha'],
  ['Rourkela', 'Odisha'], ['Berhampur', 'Odisha'], ['Sambalpur', 'Odisha'],
  ['Ranchi', 'Jharkhand'], ['Jamshedpur', 'Jharkhand'],
  ['Dhanbad', 'Jharkhand'], ['Bokaro', 'Jharkhand'],
  ['Raipur', 'Chhattisgarh'], ['Bhilai', 'Chhattisgarh'],
  ['Bilaspur', 'Chhattisgarh'], ['Korba', 'Chhattisgarh'],
  ['Guwahati', 'Assam'], ['Dibrugarh', 'Assam'],
  ['Silchar', 'Assam'], ['Jorhat', 'Assam'],
  ['Dehradun', 'Uttarakhand'], ['Haridwar', 'Uttarakhand'],
  ['Roorkee', 'Uttarakhand'], ['Haldwani', 'Uttarakhand'],
  ['Shimla', 'Himachal Pradesh'], ['Dharamshala', 'Himachal Pradesh'],
  ['Mandi', 'Himachal Pradesh'], ['Solan', 'Himachal Pradesh'],
  ['Panaji', 'Goa'], ['Margao', 'Goa'], ['Vasco da Gama', 'Goa'],
  ['Srinagar', 'Jammu and Kashmir'], ['Jammu', 'Jammu and Kashmir'],
  ['Leh', 'Ladakh'],
  ['Imphal', 'Manipur'], ['Shillong', 'Meghalaya'],
  ['Aizawl', 'Mizoram'], ['Kohima', 'Nagaland'],
  ['Agartala', 'Tripura'], ['Gangtok', 'Sikkim'],
  ['Itanagar', 'Arunachal Pradesh'], ['Puducherry', 'Puducherry'],
  ['Port Blair', 'Andaman and Nicobar Islands'],
];
