// Indian name pool for the live-stream bot audience.
//
// Curated mix across regions (North, South, East, West) so a live
// chat doesn't read as one community. About 70% of generated bots
// get a first + surname, ~30% get a single name only - mirrors a
// realistic Indian social-app audience. The pools are intentionally
// medium-sized (~120 first names, ~80 surnames) so 5000 generated
// bots have plenty of variety without obvious duplicates.

export const FIRST_NAMES = [
  // North + Hindi-belt
  'Aarav', 'Aarush', 'Aditya', 'Akash', 'Aman', 'Ankit', 'Anurag',
  'Arjun', 'Ashish', 'Ayush', 'Bhavesh', 'Chirag', 'Deepak', 'Devansh',
  'Dhruv', 'Divyansh', 'Gaurav', 'Harsh', 'Himanshu', 'Ishaan',
  'Jatin', 'Karan', 'Kartik', 'Krish', 'Lakshay', 'Manish', 'Mayank',
  'Mohit', 'Naman', 'Naveen', 'Nikhil', 'Nitin', 'Parth', 'Piyush',
  'Pranav', 'Prateek', 'Rahul', 'Raj', 'Rajeev', 'Rakesh', 'Rishabh',
  'Rohan', 'Rohit', 'Sahil', 'Sameer', 'Sandeep', 'Sanjay', 'Saurabh',
  'Shashank', 'Shivam', 'Shubham', 'Siddharth', 'Sumit', 'Suraj',
  'Tarun', 'Tushar', 'Utkarsh', 'Varun', 'Vibhor', 'Vikas', 'Vikram',
  'Vinay', 'Vipul', 'Vivek', 'Yash', 'Yogesh',
  // Female
  'Aditi', 'Aishwarya', 'Akshara', 'Ananya', 'Anika', 'Anjali',
  'Anushka', 'Aradhya', 'Arushi', 'Avantika', 'Bhavna', 'Bhumika',
  'Chitra', 'Deepika', 'Disha', 'Divya', 'Falguni', 'Garima', 'Gauri',
  'Geetika', 'Heena', 'Ishita', 'Jaya', 'Jyoti', 'Kajal', 'Kanika',
  'Kavya', 'Khushi', 'Komal', 'Kriti', 'Lavanya', 'Mahima', 'Mallika',
  'Manisha', 'Megha', 'Mira', 'Mrinalini', 'Naina', 'Namrata',
  'Nandini', 'Neha', 'Nidhi', 'Niharika', 'Pallavi', 'Pooja', 'Pratiksha',
  'Preeti', 'Priya', 'Radhika', 'Rashmi', 'Reena', 'Riddhi', 'Riya',
  'Saanvi', 'Sakshi', 'Sanya', 'Saumya', 'Shalini', 'Shivani',
  'Shreya', 'Shruti', 'Simran', 'Sneha', 'Sonal', 'Sonali', 'Sukanya',
  'Swati', 'Tanvi', 'Tejal', 'Trisha', 'Vaishnavi', 'Vandana', 'Vanya',
  'Vidya', 'Yashika',
  // South
  'Adithya', 'Anand', 'Anantha', 'Balaji', 'Bharath', 'Chethan',
  'Dinesh', 'Gopal', 'Hari', 'Karthik', 'Kishore', 'Manoj', 'Mukesh',
  'Murali', 'Naga', 'Naren', 'Praveen', 'Raghav', 'Rajan', 'Rakshith',
  'Ramesh', 'Ravi', 'Sanjay', 'Sathish', 'Sharath', 'Sridhar',
  'Srikanth', 'Suresh', 'Vignesh',
  'Anjali', 'Akhila', 'Anitha', 'Bhavya', 'Chitra', 'Deepa', 'Divya',
  'Gayathri', 'Hema', 'Jeeva', 'Kalpana', 'Lakshmi', 'Latha',
  'Mahalakshmi', 'Manasa', 'Meera', 'Nayana', 'Padma', 'Priyanka',
  'Ramya', 'Sangeetha', 'Saraswathi', 'Shanthi', 'Sindhu', 'Sruthi',
  'Sumathi', 'Sushma', 'Swetha', 'Uma', 'Vidhya',
  // East / Bengal
  'Abhijit', 'Anirban', 'Arindam', 'Avik', 'Bidisha', 'Debasish',
  'Indrajit', 'Joydeep', 'Krishanu', 'Mainak', 'Mithun', 'Pritam',
  'Rituparna', 'Sayan', 'Sourav', 'Subhajit', 'Sumanta', 'Surajit',
  'Tanmoy', 'Tridib',
  'Ananya', 'Anushree', 'Aparajita', 'Aratrika', 'Banhi', 'Chandrima',
  'Madhumita', 'Moushumi', 'Paramita', 'Pousali', 'Rimi', 'Rini',
  'Roshni', 'Sanchita', 'Sayantani', 'Shreyasi', 'Sneha', 'Sohini',
  'Suchismita', 'Tania',
  // West / Maharashtra + Gujarat
  'Aaditya', 'Aniket', 'Atharv', 'Chinmay', 'Hrishikesh', 'Kaustubh',
  'Mandar', 'Mihir', 'Nachiket', 'Nilesh', 'Onkar', 'Parikshit',
  'Pranjal', 'Prasad', 'Rugved', 'Salil', 'Samir', 'Shantanu',
  'Shrikant', 'Soham', 'Suyash', 'Tanmay', 'Uddhav', 'Vihaan', 'Yash',
  'Aboli', 'Aishwarya', 'Amruta', 'Aparna', 'Bhakti', 'Ketaki',
  'Madhura', 'Mrunmayee', 'Mugdha', 'Pooja', 'Pranjal', 'Renuka',
  'Rutuja', 'Sayali', 'Shraddha', 'Sneha', 'Snehal', 'Sonali',
  'Tejaswini', 'Vrinda', 'Yashodhara',
];

export const SURNAMES = [
  // North
  'Sharma', 'Verma', 'Singh', 'Gupta', 'Mishra', 'Tiwari', 'Kapoor',
  'Mehra', 'Khanna', 'Malhotra', 'Chopra', 'Sethi', 'Bansal', 'Arora',
  'Aggarwal', 'Kumar', 'Yadav', 'Jha', 'Pandey', 'Dubey', 'Trivedi',
  'Chauhan', 'Rathore', 'Chandra', 'Saxena', 'Dixit', 'Joshi',
  'Bhardwaj', 'Mathur', 'Vashisht',
  // South
  'Iyer', 'Iyengar', 'Nair', 'Menon', 'Pillai', 'Naidu', 'Raju',
  'Reddy', 'Rao', 'Gowda', 'Hegde', 'Bhat', 'Shetty', 'Krishnan',
  'Subramaniam', 'Murthy', 'Acharya', 'Kamath', 'Pai', 'Prabhu',
  'Sastry', 'Venkataraman', 'Padmanabhan',
  // East
  'Banerjee', 'Bhattacharya', 'Chatterjee', 'Mukherjee', 'Ghosh',
  'Sen', 'Das', 'Dutta', 'Saha', 'Roy', 'Pal', 'Bose', 'Bhowmik',
  'Kar', 'Maity', 'Mitra',
  // West
  'Patel', 'Shah', 'Mehta', 'Desai', 'Joshi', 'Trivedi', 'Pandya',
  'Vyas', 'Thakkar', 'Parekh', 'Modi', 'Patil', 'Kulkarni', 'Deshmukh',
  'Joshi', 'Bhosale', 'Pawar', 'Salunkhe', 'Gokhale', 'Kelkar',
  // Pan-India
  'Khan', 'Ahmed', 'Ali', 'Hussain', 'Sheikh', 'Qureshi',
];

// Curated question pool for the bot audience. Every line is short,
// sounds like a real viewer, contains NO em-dashes or hyphens.
// 200 entries, no duplicates - admin can extend via /admin-live-bots
// question tab and the same uniqueness is enforced there.
export const SEED_QUESTIONS = [
  'Sir when will I get a government job?',
  'Madam please tell me about my marriage',
  'When can I start my own business?',
  'My career feels stuck. What should I do?',
  'When will my financial troubles end?',
  'Will I get a promotion this year?',
  'Sir is mangal dosha bad in my chart?',
  'When will I get married please tell?',
  'Madam I am very confused about studies',
  'Will I clear my exam this attempt?',
  'My husband is angry always why?',
  'Will I have a love marriage or arranged?',
  'Sir which gemstone should I wear?',
  'My business is in loss what to do?',
  'When can I travel abroad?',
  'Madam will I get a child soon?',
  'My family is not supporting me',
  'Will my parents agree for love marriage?',
  'Sir what about my health this year?',
  'When will I buy my own house?',
  'Will I get foreign job opportunity?',
  'Madam please tell about higher studies',
  'My partner is not loyal what to do?',
  'When will sade sati end for me?',
  'Will I get success in IAS exam?',
  'Sir when can I buy a car?',
  'My mother is unwell please pray',
  'Will my court case end in my favour?',
  'When will I get back my money?',
  'Sir is my chart strong for politics?',
  'My elder brother is jealous of me',
  'When will my engagement happen?',
  'Will my MBA admission come through?',
  'Sir I want to settle in Canada',
  'My job interview is next week sir',
  'When will my husband come back home?',
  'Will I become a doctor or engineer?',
  'My father is not talking to me',
  'When will my dosha go away?',
  'Sir my Saturn is heavy in chart',
  'Will my new venture succeed?',
  'Madam I have a competitor problem',
  'When can I sell my old property?',
  'Will my second child be a son?',
  'Sir is my saturn return ending soon?',
  'My neighbour is doing kala jadu on me',
  'When will my brother get a job?',
  'Will my parents recover health soon?',
  'Sir please suggest a daily mantra',
  'When can I move to Bangalore?',
  'Will my divorce be final this year?',
  'My boss is unfair please tell',
  'When will I become rich one day?',
  'Sir which colour is lucky for me?',
  'My mother in law is not happy',
  'Will my pregnancy be smooth?',
  'When will my husband get promotion?',
  'Sir is Rahu giving me bad results?',
  'My online business is not picking up',
  'Will I get a love marriage soon?',
  'Madam my child is not eating well',
  'When will my dream job happen?',
  'Will my new house bring luck?',
  'Sir please tell about my career change',
  'My partner does not understand me',
  'When will my visa get approved?',
  'Will I get IIT seat this year?',
  'Sir my career is in IT will it grow?',
  'My sister is unwell since last month',
  'When will my second marriage happen?',
  'Will my dosha cancel after puja?',
  'Madam I want to move abroad',
  'My investment is stuck please advise',
  'When will I buy gold for daughter?',
  'Will my elder daughter get good husband?',
  'Sir what about my younger son future?',
  'My business partner is cheating me',
  'When will my Saturn period end?',
  'Will I get bank PO job this year?',
  'Sir please tell about my next year',
  'My senior is creating problem at work',
  'When can I start a YouTube channel?',
  'Will my food business succeed?',
  'Madam is my chart good for music career?',
  'My elder son is not studying well',
  'When will my new car bring luck?',
  'Will my younger sister get married soon?',
  'Sir please suggest a remedy for fear',
  'My night sleep is very disturbed',
  'When will my brother return from Dubai?',
  'Will my new shop have customers?',
  'Sir is mars strong in my chart?',
  'My husband works in army please bless',
  'When will my old loan close?',
  'Will my next job have higher salary?',
  'Madam my son is appearing for NEET',
  'My father wants me to marry soon',
  'When will I have my own startup?',
  'Will my elder daughter clear UPSC?',
  'Sir my health is not good lately',
  'My uncle is causing family tension',
  'When can I expect transfer to home town?',
  'Will my parents bless this match?',
  'Sir is my moon weak in chart?',
  'My fiance is not picking my calls',
  'When will my career take off?',
  'Will my online classes get students?',
  'Madam I want to learn vedic astrology',
  'My grandfather is very ill please pray',
  'When will my new shop open?',
  'Will my younger brother go abroad?',
  'Sir please suggest a fast for Saturn',
  'My elder sister got married recently',
  'When can I expect first salary credit?',
  'Will my college placement happen well?',
  'Sir my Jupiter is in 6th house',
  'My mother is worried about my marriage',
  'When will my husband transfer happen?',
  'Will my new business need more capital?',
  'Madam please tell about my soulmate',
  'My boss is shifting me to other team',
  'When will my Mars period start?',
  'Will my girlfriend agree for marriage?',
  'Sir is my Venus giving good results?',
  'My elder daughter wants to study abroad',
  'When can I expect my CIBIL to improve?',
  'Will my old debt be cleared this year?',
  'Sir please tell about real estate luck',
  'My in laws are demanding more dowry',
  'When will my son start walking?',
  'Will my younger child get top marks?',
  'Madam I am facing constant headache',
  'My senior at office is harassing me',
  'When can I expect my next baby?',
  'Will my elder son join IIM?',
  'Sir is my Mercury strong for business?',
  'My wife is angry with me lately',
  'When will I move to my dream city?',
  'Will my new flat bring positivity?',
  'Sir please tell about Kalsarp dosha',
  'My father is asking me to take over shop',
  'When can I get government scholarship?',
  'Will my brother in law support us?',
  'Madam my mother is widow please bless',
  'My partner wants to move abroad',
  'When will my book be published?',
  'Will my parents bless our love?',
  'Sir please tell about my second child',
  'My elder son is in army please pray',
  'When can I expect overseas posting?',
  'Will my daughter get a kind husband?',
  'Sir is my Ketu causing detachment?',
  'My uncle is taking our family property',
  'When will my long pending case close?',
  'Will my new startup get investors?',
  'Madam I want to buy a farm house',
  'My fiance family is delaying wedding',
  'When can I expect a baby boy?',
  'Will my second son become engineer?',
  'Sir please tell about jewellery business',
  'My elder daughter is unmarried at 30',
  'When will my fitness improve sir?',
  'Will my online shop start selling more?',
  'Sir is my Rahu in tenth house bad?',
  'My grandmother is asking about marriage',
  'When can I take a foreign trip?',
  'Will my second baby be healthy?',
  'Madam please tell about my US visa',
  'My elder brother is not helping family',
  'When will I become financially free?',
  'Will my old car finally sell?',
  'Sir please tell about my home loan',
  'My elder son wants to be a chef',
  'When can I expect property partition?',
  'Will my marriage have love and respect?',
  'Sir is my Sun strong for politics?',
  'My in laws live far please advise',
  'When will my younger child speak?',
  'Will my elder son get IIT Delhi?',
  'Madam I want to become a teacher',
  'My partner is non vegetarian I am not',
  'When can I afford a second home?',
  'Will my husband get army posting near?',
  'Sir please tell about my next vehicle',
  'My elder daughter is doing CA exam',
  'When will I have peace at home?',
  'Will my elder son become a pilot?',
  'Sir is Jupiter in eleventh good?',
  'My family is small but joint please advise',
  'When can I retire and travel?',
  'Will my second son become a doctor?',
  'Madam I am worried about loneliness',
  'My elder brother is in foreign country',
  'When will I get inner peace sir?',
  'Will my new venture clear pending dues?',
  'Sir please tell about my parents health',
  'My friend is starting a venture with me',
  'When will my elder son marry?',
  'Will my mother find peace this year?',
  'Sir is my chart strong for media?',
  'My senior at college is misbehaving',
  'When can I expect a job offer abroad?',
  'Will my elder son get a kind wife?',
  'Madam please tell about my late father',
];
