// One-shot: change Android/iOS bundle IDs off "astroconnect" entirely.
//
//   client-web  com.astroconnect.app        -> com.astroseer.app
//   astro-web   com.astroconnect.astrologer -> com.astroseer.astrologer
//   admin-web   com.astroconnect.admin      -> com.astroseer.admin
//   root scaffold com.vickymartin.astroconnect -> com.astroseer.app
//
// Touches: capacitor.config.json (appId), android build.gradle
// (namespace + applicationId), strings.xml (package_name +
// custom_url_scheme), the generated assets/capacitor.config.json, and
// MOVES the MainActivity.java into the new package directory (Gradle
// `namespace` must match the Java package). google-services*.json are
// NOT edited - they are Firebase-signed and must be regenerated by the
// user for the new IDs; patch-native simply skips them until then.
import {
  readFileSync, writeFileSync, existsSync, mkdirSync, rmSync,
  readdirSync,
} from 'fs';
import { join, dirname } from 'path';

const ROOT = process.cwd();
const MAP = {
  'client-web': { old: 'com.astroconnect.app', neu: 'com.astroseer.app' },
  'astro-web': { old: 'com.astroconnect.astrologer', neu: 'com.astroseer.astrologer' },
  'admin-web': { old: 'com.astroconnect.admin', neu: 'com.astroseer.admin' },
  '.': { old: 'com.vickymartin.astroconnect', neu: 'com.astroseer.app' },
};

const swap = (rel, oldId, neu) => {
  const f = join(ROOT, rel);
  if (!existsSync(f)) return null;
  const b = readFileSync(f, 'utf8');
  if (!b.includes(oldId)) return `  (no '${oldId}' in ${rel})`;
  writeFileSync(f, b.split(oldId).join(neu));
  return `  ${rel}: ${oldId} -> ${neu}`;
};

for (const [app, { old, neu }] of Object.entries(MAP)) {
  const base = app === '.' ? '' : app + '/';
  console.log(`\n=== ${app} (${old} -> ${neu}) ===`);
  for (const rel of [
    `${base}capacitor.config.json`,
    `${base}android/app/build.gradle`,
    `${base}android/app/src/main/res/values/strings.xml`,
    `${base}android/app/src/main/assets/capacitor.config.json`,
  ]) {
    const r = swap(rel, old, neu);
    if (r) console.log(r);
  }
  // Move MainActivity.java old-package-dir -> new-package-dir.
  const javaRoot = join(ROOT, base, 'android/app/src/main/java');
  if (existsSync(javaRoot)) {
    const oldPath = join(javaRoot, ...old.split('.'), 'MainActivity.java');
    const newPath = join(javaRoot, ...neu.split('.'), 'MainActivity.java');
    if (existsSync(oldPath)) {
      const src = readFileSync(oldPath, 'utf8')
        .split(`package ${old};`).join(`package ${neu};`)
        .split(old).join(neu);
      mkdirSync(dirname(newPath), { recursive: true });
      writeFileSync(newPath, src);
      rmSync(oldPath);
      // Prune now-empty old package dirs (stop at java/).
      let d = dirname(oldPath);
      while (d !== javaRoot && existsSync(d) && readdirSync(d).length === 0) {
        rmSync(d, { recursive: true, force: true });
        d = dirname(d);
      }
      console.log(`  java: moved MainActivity ${old} -> ${neu}`);
    } else {
      console.log(`  java: MainActivity not at ${old} (skipped)`);
    }
  }
}

// patch-native PKG map (root google-services.json install gate).
{
  const f = join(ROOT, 'scripts/patch-native.mjs');
  let b = readFileSync(f, 'utf8');
  b = b.replace("'client-web': 'com.astroconnect.app'",
    "'client-web': 'com.astroseer.app'")
    .replace("'astro-web': 'com.astroconnect.astrologer'",
      "'astro-web': 'com.astroseer.astrologer'");
  writeFileSync(f, b);
  console.log('\npatch-native PKG map -> com.astroseer.*');
}

// iOS GoogleService-Info.plist BUNDLE_ID (file itself must be replaced
// by the user with a fresh Firebase download; this keeps it consistent).
{
  const f = join(ROOT, 'GoogleService-Info.plist');
  if (existsSync(f)) {
    let b = readFileSync(f, 'utf8');
    b = b.split('com.astroconnect.app').join('com.astroseer.app');
    writeFileSync(f, b);
    console.log('GoogleService-Info.plist BUNDLE_ID -> com.astroseer.app');
  }
}

console.log('\nrepackage done.');
