// Sample data for seeding (run via scripts/seed.mjs).
export const ASTROLOGERS = [
  { name: 'Pandit Ravi Sharma', skills: ['Vedic', 'KP'],
    languages: ['Hindi', 'English'], experience: 22, priceChat: 30,
    priceCall: 40, priceVideo: 55, discountPercent: 0, rating: 4.8,
    status: 'online', img: 'men/32',
    bio: 'Vedic and KP specialist with 22 years guiding clients on career, marriage and remedies. Calm, practical and remedy-focused.' },
  { name: 'Acharya Meena Iyer', skills: ['Tarot', 'Numerology'],
    languages: ['English', 'Tamil'], experience: 15, priceChat: 24,
    priceCall: 35, priceVideo: 50, discountPercent: 25, rating: 4.6,
    status: 'online', img: 'women/44',
    bio: 'Tarot and numerology reader. Honest, compassionate guidance on love and life decisions.' },
  { name: 'Vivek Joshi', skills: ['Career', 'Finance', 'Vedic'],
    languages: ['Hindi', 'Gujarati'], experience: 17, priceChat: 20,
    priceCall: 30, priceVideo: 45, discountPercent: 0, rating: 4.7,
    status: 'busy', img: 'men/51',
    bio: 'Pragmatic career and finance counsel grounded in dasha analysis. Direct, actionable guidance.' },
  { name: 'Acharya Vedic Anand', skills: ['Vedic', 'KP', 'Dasha'],
    languages: ['Hindi', 'English', 'Sanskrit'], experience: 20,
    priceChat: 0, priceCall: 25, priceVideo: 40, discountPercent: 0,
    rating: 4.9, status: 'online', img: 'men/22',
    bio: 'Traditional Vedic scholar. Deep chart reading with classical remedies and mantra guidance.' },
  { name: 'Tara Tarot', skills: ['Tarot', 'Intuitive'],
    languages: ['English', 'Hindi'], experience: 12, priceChat: 0,
    priceCall: 20, priceVideo: 35, discountPercent: 0, rating: 4.9,
    status: 'online', img: 'women/68',
    bio: 'Intuitive tarot readings focused on clarity, timing and emotional healing.' },
  { name: 'Mira Love', skills: ['Love', 'Relationships'],
    languages: ['English', 'Hindi'], experience: 10, priceChat: 0,
    priceCall: 22, priceVideo: 40, discountPercent: 0, rating: 4.8,
    status: 'idle', img: 'women/26',
    bio: 'Relationship and marriage compatibility expert. Warm, non-judgemental and solution-driven.' },
  { name: 'Raghav Career', skills: ['Career', 'Finance'],
    languages: ['Hindi', 'English'], experience: 14, priceChat: 28,
    priceCall: 38, priceVideo: 52, discountPercent: 50, rating: 4.5,
    status: 'online', img: 'men/14',
    bio: 'Specialises in job timing, business growth and financial decisions using KP and transits.' },
  { name: 'Saira Spirit', skills: ['Spiritual', 'Meditation'],
    languages: ['English', 'Urdu'], experience: 18, priceChat: 26,
    priceCall: 36, priceVideo: 50, discountPercent: 0, rating: 4.7,
    status: 'busy', img: 'women/12',
    bio: 'Spiritual guidance, energy healing and meditation practices for inner peace and direction.' },
  { name: 'Pandit Vivah Kumar', skills: ['Guna Milan', 'Marriage'],
    languages: ['Hindi', 'Bhojpuri'], experience: 21, priceChat: 32,
    priceCall: 42, priceVideo: 58, discountPercent: 0, rating: 4.9,
    status: 'online', img: 'men/8',
    bio: 'Marriage matching and Manglik dosha specialist. Detailed Ashtakoot analysis and remedies.' },
  { name: 'Guru Anand Mishra', skills: ['Vastu', 'Palmistry'],
    languages: ['Hindi', 'English', 'Punjabi'], experience: 30,
    priceChat: 30, priceCall: 45, priceVideo: 60, discountPercent: 0,
    rating: 4.9, status: 'idle', img: 'men/60',
    bio: 'Three decades in Vastu and palmistry. Trusted for home, property and life-path guidance.' },
  { name: 'Saira Kapoor', skills: ['Love', 'Marriage'],
    languages: ['English', 'Hindi'], experience: 9, priceChat: 15,
    priceCall: 25, priceVideo: 38, discountPercent: 25, rating: 4.4,
    status: 'online', img: 'women/33',
    bio: 'Friendly love and marriage advisor. Quick, practical answers for everyday relationship questions.' },
  { name: 'Acharya Devdatta', skills: ['Vedic', 'Numerology', 'Remedies'],
    languages: ['Hindi', 'Marathi', 'English'], experience: 25,
    priceChat: 35, priceCall: 48, priceVideo: 65, discountPercent: 0,
    rating: 4.8, status: 'offline', img: 'men/76',
    bio: 'Senior Vedic astrologer and numerologist. Strong on career turning points and life remedies.' },
];

export const REVIEW_TEXTS = [
  'Very accurate prediction, felt heard and guided. Thank you!',
  'Clear and to the point. The remedies actually helped.',
  'Calm and patient. Explained everything in detail.',
  'Spot on about my career timing. Highly recommended.',
  'Kind and honest reading, no false promises.',
  'Helped me a lot with my marriage decision. Grateful.',
  'Quick response and very practical advice.',
  'Deep knowledge of Vedic astrology. Will consult again.',
  'Reassuring and positive. Made my day better.',
  'Excellent tarot session, very insightful.',
];

export const REPLIES = [
  'Thank you for your kind words. Stay blessed!',
  'Glad I could help. Do the remedies regularly.',
  'Wishing you the best ahead. Reach out anytime.',
  '',
];
